//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gobchat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gobchat.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking complete.
        /// </summary>
        internal static string Core_Util_ArchiveUnpacker_Complete {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpacker.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file: {0}.
        /// </summary>
        internal static string Core_Util_ArchiveUnpacker_DeleteFile {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpacker.DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete partially unpacked archive.
        /// </summary>
        internal static string Core_Util_ArchiveUnpacker_DeleteIncomplete {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpacker.DeleteIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking cancelled.
        /// </summary>
        internal static string Core_Util_ArchiveUnpackerHelper_Canceled {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpackerHelper.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking complete.
        /// </summary>
        internal static string Core_Util_ArchiveUnpackerHelper_Complete {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpackerHelper.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking.
        /// </summary>
        internal static string Core_Util_ArchiveUnpackerHelper_Unpack {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpackerHelper.Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking: {0}.
        /// </summary>
        internal static string Core_Util_ArchiveUnpackerHelper_UnpackLog {
            get {
                return ResourceManager.GetString("Core.Util.ArchiveUnpackerHelper.UnpackLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled.
        /// </summary>
        internal static string Core_Util_DownloadHelper_Canceled {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string Core_Util_DownloadHelper_Complete {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string Core_Util_DownloadHelper_Connecting {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading: {0} of {1}.
        /// </summary>
        internal static string Core_Util_DownloadHelper_Download {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare download.
        /// </summary>
        internal static string Core_Util_DownloadHelper_Prepare {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        internal static string Core_Util_DownloadHelper_Waiting {
            get {
                return ResourceManager.GetString("Core.Util.DownloadHelper.Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: {0}.
        /// </summary>
        internal static string GeneralErrorOccured {
            get {
                return ResourceManager.GetString("GeneralErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GobIcon {
            get {
                object obj = ResourceManager.GetObject("GobIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GobTrayIconOff {
            get {
                object obj = ResourceManager.GetObject("GobTrayIconOff", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GobTrayIconOn {
            get {
                object obj = ResourceManager.GetObject("GobTrayIconOn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI requires additional components (CEF). They will be downloaded and unpacked.
        ///Continue?.
        /// </summary>
        internal static string Module_Cef_Dialog_CefMissing_Text {
            get {
                return ResourceManager.GetString("Module.Cef.Dialog.CefMissing.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEF installation failed. Reason:
        ///{0}
        ///
        ///Retry or install CEF manually for gobchat..
        /// </summary>
        internal static string Module_Cef_Dialog_InstallFailed_Text {
            get {
                return ResourceManager.GetString("Module.Cef.Dialog.InstallFailed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Module_Cef_Dialog_InstallFailed_Title {
            get {
                return ResourceManager.GetString("Module.Cef.Dialog.InstallFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete partially downloaded cef archive: {0}.
        /// </summary>
        internal static string Module_Cef_Installer_Download_DeleteIncomplete {
            get {
                return ResourceManager.GetString("Module.Cef.Installer.Download.DeleteIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacking complete.
        /// </summary>
        internal static string Module_Cef_Installer_Unpack_Complete {
            get {
                return ResourceManager.GetString("Module.Cef.Installer.Unpack.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete partially unpacked CEF archive: {0}.
        /// </summary>
        internal static string Module_Cef_Installer_Unpack_DeleteIncomplete {
            get {
                return ResourceManager.GetString("Module.Cef.Installer.Unpack.DeleteIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hotkey for {0}: {1}.
        /// </summary>
        internal static string Module_Hotkey_ConfigHotkeyUpdater_InvalidHotkey {
            get {
                return ResourceManager.GetString("Module.Hotkey.ConfigHotkeyUpdater.InvalidHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access FFXIV chatlog. Restart Gobchat with admin rights..
        /// </summary>
        internal static string Module_Misc_Connection_AdminRights {
            get {
                return ResourceManager.GetString("Module.Misc.Connection.AdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFXIV detected..
        /// </summary>
        internal static string Module_Misc_Connection_Found {
            get {
                return ResourceManager.GetString("Module.Misc.Connection.Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find a running instance of FFXIV..
        /// </summary>
        internal static string Module_Misc_Connection_NotFound {
            get {
                return ResourceManager.GetString("Module.Misc.Connection.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp; Hide.
        /// </summary>
        internal static string Module_Misc_Hotkey_ShowHide {
            get {
                return ResourceManager.GetString("Module.Misc.Hotkey.ShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Module_NotifyIcon_UI_Close {
            get {
                return ResourceManager.GetString("Module.NotifyIcon.UI.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string Module_NotifyIcon_UI_Hide {
            get {
                return ResourceManager.GetString("Module.NotifyIcon.UI.Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Module_NotifyIcon_UI_Reload {
            get {
                return ResourceManager.GetString("Module.NotifyIcon.UI.Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset overlay.
        /// </summary>
        internal static string Module_NotifyIcon_UI_Reset {
            get {
                return ResourceManager.GetString("Module.NotifyIcon.UI.Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Module_NotifyIcon_UI_Show {
            get {
                return ResourceManager.GetString("Module.NotifyIcon.UI.Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save profiles to disk. See debug log for more information..
        /// </summary>
        internal static string Module_UI_Connector_Config_Profile_Error {
            get {
                return ResourceManager.GetString("Module.UI.Connector.Config.Profile.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles saved..
        /// </summary>
        internal static string Module_UI_Connector_Config_Profile_Saved {
            get {
                return ResourceManager.GetString("Module.UI.Connector.Config.Profile.Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download newest version.
        ///Reason: {0}.
        /// </summary>
        internal static string Module_Updater_Dialog_DownloadFailed_Text {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.DownloadFailed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Module_Updater_Dialog_DownloadFailed_Title {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.DownloadFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract archive.
        ///Reason: {0}.
        /// </summary>
        internal static string Module_Updater_Dialog_ExtractionFailed_Text {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.ExtractionFailed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Module_Updater_Dialog_ExtractionFailed_Title {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.ExtractionFailed.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressing Yes will close Gobchat and opens a webpage instead, which will provide the newest version for Gobchat.
        ///
        ///Download gobchat-{0}.zip and overwrite your current Gobchat..
        /// </summary>
        internal static string Module_Updater_Dialog_ManualInstall_Text {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.ManualInstall.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual installation.
        /// </summary>
        internal static string Module_Updater_Dialog_ManualInstall_Title {
            get {
                return ResourceManager.GetString("Module.Updater.Dialog.ManualInstall.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file: {0}.
        /// </summary>
        internal static string Module_Updater_UI_Log_DeleteFile {
            get {
                return ResourceManager.GetString("Module.Updater.UI.Log.DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for shutdown.
        /// </summary>
        internal static string Module_Updater_UI_Log_Done {
            get {
                return ResourceManager.GetString("Module.Updater.UI.Log.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare installation of update.
        /// </summary>
        internal static string Module_Updater_UI_Log_PrepareUpdates {
            get {
                return ResourceManager.GetString("Module.Updater.UI.Log.PrepareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updates for installation found..
        /// </summary>
        internal static string Module_Updater_UI_Log_UpdateCount {
            get {
                return ResourceManager.GetString("Module.Updater.UI.Log.UpdateCount", resourceCulture);
            }
        }
    }
}
